### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by csigritz** [oschni/Corona-Ampel-Bayern#1]
Currently in the widget `hospitalizationLast7Days` and `currentIntensiveCarePatients` are used to display the current state of the lights. This is correct, but does not reflect the official state announced by the government.
The official current state is always stored in `officialState`. If there is an announced switch of the state, the object `nextSwitch` will display this, otherwise it is null.

Maybe change the widget to use the official state value?

Possible states:
```
'green'
'yellow'
'red'
```

```json
{
  "hospitalizationLast7Days": 709,
  "hospitalizationLast7DaysIncidence": 5.4,
  "currentIntensiveCarePatients": 630,
  "lastSync": "2021-11-09T08:00:02.865Z",
  "lastUpdate": "2021-11-09T08:00:07.505Z",
  "state": "red",
  "officialState": "red",
  "nextSwitch": null,
  "yellowPercent": 140,
  "redPercent": 105
}
```

Possible value for nextSwitch:
```json
{
  "date": "2021-09-11",
  "state": "red"
}
```

**Comment by oschni** [comment]
Thank you for informations. I changed the code to use the "officeState" value.
